### ISSUE TITLE
Error: Cannot find module './routes' 

### ISSUE THREAD

**Issue by ik-brahim** [kolson25/WebRTC-Multi-Peer-Video-Audio#5]
hi 
when executing  node app.js
i get this erreur
------------------------------------------------------
internal/modules/cjs/loader.js:638
    throw err;
    ^

Error: Cannot find module './routes'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:636:15)
    at Function.Module._load (internal/modules/cjs/loader.js:562:25)
    at Module.require (internal/modules/cjs/loader.js:692:17)
    at require (internal/modules/cjs/helpers.js:25:18)
    at Object.<anonymous> (/var/www/html/b/WebRTC-Multi-Peer-Video-Audio/server/app.js:2:14)
    at Module._compile (internal/modules/cjs/loader.js:778:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
------------------------------------------------
can i get some help please

**Comment by kwonyuseong** [comment]
https://github.com/kolson25/WebRTC-Multi-Peer-Video-Audio/issues/2

**Comment by suyashcjoshi** [comment]
Same issue here, any fix ?
